"""escalerilla lote y descripcion

Revision ID: 19a3314bcd94
Revises: 257d4fea4035
Create Date: 2025-06-14 18:23:04.357412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a3314bcd94'
down_revision: Union[str, None] = '257d4fea4035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulls', sa.Column('lote', sa.String(length=100), nullable=True))
    op.add_column('bulls', sa.Column('escalerilla', sa.String(length=100), nullable=True))
    op.add_column('bulls', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulls', 'description')
    op.drop_column('bulls', 'escalerilla')
    op.drop_column('bulls', 'lote')
    # ### end Alembic commands ###
