"""cambios en opus race donante_code

Revision ID: 257d4fea4035
Revises: 5ba01d066c0f
Create Date: 2025-06-14 09:02:50.828813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '257d4fea4035'
down_revision: Union[str, None] = '5ba01d066c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opus', sa.Column('race', sa.String(length=50), nullable=False))
    op.add_column('opus', sa.Column('donante_code', sa.String(length=100), nullable=False))
    op.alter_column('opus', 'donante_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opus', 'donante_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('opus', 'donante_code')
    op.drop_column('opus', 'race')
    # ### end Alembic commands ###
