"""add lugar and finca to opus

Revision ID: 3f114334f288
Revises: add_toro_id_to_opus_001
Create Date: 2025-06-11 07:28:29.113697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f114334f288'
down_revision: Union[str, None] = 'add_toro_id_to_opus_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('races', 'name',
    #            existing_type=mysql.VARCHAR(length=50),
    #            type_=sa.String(length=100),
    #            existing_nullable=False)
    # op.alter_column('races', 'description',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('races', 'code',
    #            existing_type=mysql.VARCHAR(length=20),
    #            type_=sa.String(length=10),
    #            existing_nullable=False)
    # op.alter_column('sexes', 'name',
    #            existing_type=mysql.VARCHAR(length=20),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    
    op.add_column('opus', sa.Column('lugar', sa.String(length=100), nullable=True))
    op.add_column('opus', sa.Column('finca', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('sexes', 'name',
    #            existing_type=sa.String(length=50),
    #            type_=mysql.VARCHAR(length=20),
    #            existing_nullable=False)
    # op.alter_column('races', 'code',
    #            existing_type=sa.String(length=10),
    #            type_=mysql.VARCHAR(length=20),
    #            existing_nullable=False)
    # op.alter_column('races', 'description',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('races', 'name',
    #            existing_type=sa.String(length=100),
    #            type_=mysql.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_column('opus', 'finca')
    op.drop_column('opus', 'lugar')
    # ### end Alembic commands ###
