"""campo finca

Revision ID: 4f96af44682a
Revises: 97a6d5ee8959
Create Date: 2025-06-16 00:19:07.298349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f96af44682a'
down_revision: Union[str, None] = '97a6d5ee8959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produccion_embrionaria', sa.Column('finca', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produccion_embrionaria', 'finca')
    # ### end Alembic commands ###
