"""Cambio Float a Numeric

Revision ID: 5ba01d066c0f
Revises: 3f114334f288
Create Date: 2025-06-13 10:39:53.411624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ba01d066c0f'
down_revision: Union[str, None] = '3f114334f288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inputs', 'quantity_received',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('inputs', 'quantity_taken',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('inputs', 'total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('outputs', 'quantity_output',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('races', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('races', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('races', 'code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('sexes', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sexes', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('races', 'code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('races', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('races', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('outputs', 'quantity_output',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('inputs', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('inputs', 'quantity_taken',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('inputs', 'quantity_received',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
