"""relacion salida y produccion embrionaria

Revision ID: 6eebe63ef4b6
Revises: 4f96af44682a
Create Date: 2025-06-16 01:21:46.840218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eebe63ef4b6'
down_revision: Union[str, None] = '4f96af44682a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produccion_embrionaria', sa.Column('output_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produccion_embrionaria', 'output_id')
    # ### end Alembic commands ###
