"""modelo de produccion embrionaria

Revision ID: 97a6d5ee8959
Revises: 19a3314bcd94
Create Date: 2025-06-15 21:42:06.102494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a6d5ee8959'
down_revision: Union[str, None] = '19a3314bcd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produccion_embrionaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_opu', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('envase', sa.String(length=100), nullable=False),
    sa.Column('fecha_transferencia', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produccion_embrionaria_id'), 'produccion_embrionaria', ['id'], unique=False)
    op.add_column('opus', sa.Column('produccion_embrionaria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'opus', 'produccion_embrionaria', ['produccion_embrionaria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opus', type_='foreignkey')
    op.drop_column('opus', 'produccion_embrionaria_id')
    op.drop_index(op.f('ix_produccion_embrionaria_id'), table_name='produccion_embrionaria')
    op.drop_table('produccion_embrionaria')
    # ### end Alembic commands ###
