"""initial migration

Revision ID: 99ebb53a9153
Revises: 
Create Date: 2025-05-27 12:47:56.445699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ebb53a9153'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_code'), 'races', ['code'], unique=True)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sexes',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sexes_code'), 'sexes', ['code'], unique=True)
    op.create_index(op.f('ix_sexes_id'), 'sexes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('number_document', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('type_document', sa.Enum('identity_card', 'passport', 'other', name='documenttype'), nullable=False),
    sa.Column('pass_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_number_document'), 'users', ['number_document'], unique=True)
    op.create_table('bulls',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('register', sa.String(length=50), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('sex_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='bullstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['sex_id'], ['sexes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulls_id'), 'bulls', ['id'], unique=False)
    op.create_index(op.f('ix_bulls_register'), 'bulls', ['register'], unique=True)
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_user_id'), 'role_user', ['id'], unique=False)
    op.create_table('inputs',
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.Column('escalarilla', sa.String(length=100), nullable=False),
    sa.Column('bull_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Enum('pending', 'processing', 'completed', 'cancelled', name='inputstatus'), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('fv', sa.DateTime(), nullable=False),
    sa.Column('quantity_taken', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bull_id'], ['bulls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_id'), 'inputs', ['id'], unique=False)
    op.create_table('outputs',
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('output_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_output', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outputs_id'), 'outputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputs_id'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_id'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_role_user_id'), table_name='role_user')
    op.drop_table('role_user')
    op.drop_index(op.f('ix_bulls_register'), table_name='bulls')
    op.drop_index(op.f('ix_bulls_id'), table_name='bulls')
    op.drop_table('bulls')
    op.drop_index(op.f('ix_users_number_document'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sexes_id'), table_name='sexes')
    op.drop_index(op.f('ix_sexes_code'), table_name='sexes')
    op.drop_table('sexes')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_index(op.f('ix_races_code'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
