"""add toro_id to opus

Revision ID: add_toro_id_to_opus
Revises: add_opus_table_001
Create Date: 2024-03-20 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_toro_id_to_opus_001'
down_revision = 'add_opus_table_001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opus', sa.Column('toro_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_opus_toro_id_bulls', 'opus', 'bulls', ['toro_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_opus_toro_id_bulls', 'opus', type_='foreignkey')
    op.drop_column('opus', 'toro_id')
    # ### end Alembic commands ### 