"""add opus table

Revision ID: add_opus_table
Revises: 99ebb53a9153
Create Date: 2024-03-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'add_opus_table_001'
down_revision = '99ebb53a9153'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opus',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=False),
        sa.Column('donante_id', sa.Integer(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('toro', sa.String(100), nullable=False),
        sa.Column('gi', sa.Integer(), nullable=False),
        sa.Column('gii', sa.Integer(), nullable=False),
        sa.Column('giii', sa.Integer(), nullable=False),
        sa.Column('viables', sa.Integer(), nullable=False),
        sa.Column('otros', sa.Integer(), nullable=False),
        sa.Column('total_oocitos', sa.Integer(), nullable=False),
        sa.Column('ctv', sa.Integer(), nullable=False),
        sa.Column('clivados', sa.Integer(), nullable=False),
        sa.Column('porcentaje_cliv', sa.String(10), nullable=False),
        sa.Column('prevision', sa.Integer(), nullable=False),
        sa.Column('porcentaje_prevision', sa.String(10), nullable=False),
        sa.Column('empaque', sa.Integer(), nullable=False),
        sa.Column('porcentaje_empaque', sa.String(10), nullable=False),
        sa.Column('vt_dt', sa.Integer(), nullable=True),
        sa.Column('porcentaje_vtdt', sa.String(10), nullable=True),
        sa.Column('total_embriones', sa.Integer(), nullable=False),
        sa.Column('porcentaje_total_embriones', sa.String(10), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['donante_id'], ['bulls.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opus_id'), 'opus', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opus_id'), table_name='opus')
    op.drop_table('opus')
    # ### end Alembic commands ### 